'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BookOpen, ChevronLeft, ChevronRight, History, LoaderCircle, RotateCcw, Settings2, Sparkles, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';
const SUITS: Record<string, string> = { c: '♣', d: '♦', h: '♥', s: '♠' };
type LegalAction = { type: 'fold'|'check'|'call'|'raise-to'|'all-in'; amount:number|null; minAmount:number|null; maxAmount:number|null };
type Seat = { seat:number; stack:number; streetCommitted:number; handCommitted:number; status:string };
type Observation = { seed:number; button:number; street:string; board:string[]; pot:number; smallBlind:number; bigBlind:number; currentBet:number; amountToCall:number; toAct:number|null; heroSeat:number; holeCards:string[]; seats:Seat[]; actions:Array<{street:string;seat:number;type:string;amount:number}>; legalActions:LegalAction[]; result:null|{reason:string;winners:number[];payouts:number[];revealedHoleCards?:string[][]} };
type HandPayload = { sessionId:string; observation:Observation };
type Strategy = { status:string; actions:Array<{abstractAction:string;probability:number;legalAction:{type:string;amount:number|null}|null}>; diagnostics:{exactState:boolean;inferenceMs:number;warnings:string[];message:string|null} };
type HistoryItem = { sessionId:string; seed:number; status:string; startedAt:string; result:null|{reason:string;winners:number[];payouts:number[]} };
type HistoryDetail = HistoryItem & { events:Array<{sequence:number;actorSeat:number|null;action:null|{type:string;amount:number};observation:Observation;strategy:Strategy|null}> };

const cardLabel = (card:string) => `${card[0]}${SUITS[card[1]] ?? card[1]}`;
const chips = (value:number) => `${(value/100).toFixed(value%100 ? 1 : 0)} BB`;
function actionLabel(action:LegalAction) { if(action.type==='raise-to') return `Raise · ${chips(action.minAmount ?? 0)}`; if(action.type==='call') return `Call · ${chips(action.amount ?? 0)}`; if(action.type==='all-in') return 'All-in'; return action.type[0].toUpperCase()+action.type.slice(1); }
function PlayingCard({card,hidden=false}:{card?:string;hidden?:boolean}) { const value=card?cardLabel(card):''; const red=value.includes('♦')||value.includes('♥'); return <div className={`playing-card ${hidden?'card-back':''} ${red?'text-[#d9594c]':'text-[#15251f]'}`} aria-label={hidden?'Hidden card':value}>{hidden?<span className="card-back-mark">GT</span>:<span>{value}</span>}</div>; }

export default function GameClient() {
  const [hand,setHand]=useState<HandPayload|null>(null); const [strategy,setStrategy]=useState<Strategy|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const [mode,setMode]=useState<'play'|'review'>('play'); const [history,setHistory]=useState<HistoryItem[]>([]); const [review,setReview]=useState<HistoryDetail|null>(null); const [reviewStep,setReviewStep]=useState(0); const [raiseAmount,setRaiseAmount]=useState<number|null>(null);
  const request=useCallback(async<T,>(path:string,options?:RequestInit):Promise<T>=>{ const headers=new Headers(options?.headers); headers.set('Content-Type','application/json'); const response=await fetch(`${API}${path}`,{...options,headers}); const data:unknown=await response.json(); if(!response.ok){const message=typeof data==='object'&&data!==null&&'error' in data?String(data.error):`Request failed (${response.status})`;throw new Error(message);} return data as T; },[]);
  const newHand=useCallback(async()=>{ setBusy(true);setError(null);setStrategy(null);try{setHand(await request<HandPayload>('/v1/hands',{method:'POST',body:'{}'}));}catch(reason){setError(reason instanceof Error?reason.message:'Could not start a hand');}finally{setBusy(false);}},[request]);
  // oxlint-disable-next-line react/react-compiler -- initial network synchronization
  useEffect(()=>{void newHand();},[newHand]);
  async function act(action:LegalAction, amount?:number){if(!hand)return;setBusy(true);setError(null);setStrategy(null);try{const body={type:action.type,...(action.type==='raise-to'?{amount:amount??action.minAmount}:{})};setHand(await request<HandPayload>(`/v1/hands/${hand.sessionId}/actions`,{method:'POST',body:JSON.stringify(body)}));setRaiseAmount(null);}catch(reason){setError(reason instanceof Error?reason.message:'Action failed');}finally{setBusy(false);}}
  async function revealStrategy(){if(!hand)return;setBusy(true);setError(null);try{setStrategy(await request<Strategy>(`/v1/hands/${hand.sessionId}/strategy`,{method:'POST',body:'{}'}));}catch(reason){setError(reason instanceof Error?reason.message:'Strategy unavailable');}finally{setBusy(false);}}
  async function openReview(){setMode('review');setBusy(true);setError(null);try{const result=await request<{hands:HistoryItem[]}>('/v1/history?limit=30');setHistory(result.hands);if(result.hands[0])await selectHistory(result.hands[0].sessionId);}catch(reason){setError(reason instanceof Error?reason.message:'History unavailable');}finally{setBusy(false);}}
  async function selectHistory(sessionId:string){const detail=await request<HistoryDetail>(`/v1/history/${sessionId}`);setReview(detail);setReviewStep(Math.max(0,detail.events.length-1));setStrategy(null);}
  const liveObservation=hand?.observation, reviewEvent=review?.events[reviewStep], observation=mode==='review'?reviewEvent?.observation:liveObservation, hero=observation?.seats[0], opponent=observation?.seats[1], terminal=observation?.street==='terminal';
  const opponentCards=terminal&&observation?.result?.reason==='showdown'?observation.result.revealedHoleCards?.[1]:undefined;
  const recentActions=useMemo(()=>observation?.actions.slice(-5).reverse()??[],[observation]);
  const activeStrategy=mode==='review'?reviewEvent?.strategy??null:strategy;
  const legalRaise=mode==='play'?observation?.legalActions.find(item=>item.type==='raise-to'):undefined;
  const clampedRaise=legalRaise?Math.max(legalRaise.minAmount??0,Math.min(raiseAmount??legalRaise.minAmount??0,legalRaise.maxAmount??0)):0;
  const potTarget=(fraction:number)=>legalRaise?Math.max(legalRaise.minAmount??0,Math.min(Math.round((observation?.currentBet??0)+((observation?.pot??0)+(observation?.amountToCall??0))*fraction),legalRaise.maxAmount??0)):0;
  return <main className="min-h-screen bg-background text-foreground">
    <header className="app-header"><div className="brand-lockup"><span className="brand-mark"><Activity className="size-4"/></span><div><p className="brand-name">Game Trainer</p><p className="brand-subtitle">Heads-up no-limit hold’em</p></div></div><nav className="mode-switch" aria-label="Application mode"><button className={`mode-pill ${mode==='play'?'mode-pill-active':''}`} onClick={()=>setMode('play')}>Play</button><button className="mode-pill" disabled>Train</button><button className={`mode-pill ${mode==='review'?'mode-pill-active':''}`} onClick={()=>void openReview()}>Review</button></nav><div className="header-actions"><span className="local-badge"><span className={`status-dot ${error?'status-error':''}`}/>{error?'Engine offline':'Local engine'}</span><Button variant="ghost" size="icon" aria-label="Settings" disabled><Settings2/></Button></div></header>
    {mode==='review'&&<section className="history-strip"><div><History className="size-4"/><strong>Saved hands</strong></div><div className="history-list">{history.map(item=><button key={item.sessionId} className={review?.sessionId===item.sessionId?'history-active':''} onClick={()=>void selectHistory(item.sessionId)}><b>Seed {item.seed}</b><span>{item.status==='terminal'?(item.result?.winners.includes(0)?'Won':'Complete'):'In progress'}</span></button>)}</div></section>}
    <section className="workspace"><div className="table-column"><div className="session-bar"><div><span className="eyebrow">{mode==='review'?'Hand replay':'Practice hand'} · 100 BB {observation?`· Seed ${observation.seed}`:''}</span><h1>{mode==='review'?'Review the action line':terminal?(observation?.result?.winners.includes(0)?'Hand won':'Hand complete'):'Choose your action'}</h1></div><Button variant="outline" onClick={()=>{setMode('play');void newHand();}} disabled={busy}><RotateCcw/>{mode==='review'?'Back to play':'New hand'}</Button></div>
      {error&&<div className="error-banner"><TriangleAlert className="size-4"/><div><strong>Can’t reach the game engine</strong><span>{error}. Start the local API on port 8000, then try again.</span></div></div>}
      <div className="poker-table-wrap"><div className="poker-table"><div className="felt-grain"/><div className="seat opponent-seat"><div className="seat-meta"><span className="avatar">B</span><div><b>Trainer bot</b><small>{opponent?chips(opponent.stack):'—'}</small></div></div><div className="hole-cards">{opponentCards?opponentCards.map(card=><PlayingCard card={card} key={card}/>):<><PlayingCard hidden/><PlayingCard hidden/></>}</div>{observation?.button===1&&<span className="dealer-chip">D</span>}</div><div className="pot-label"><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div className="board-cards">{observation?.board.map(card=><PlayingCard card={card} key={card}/>)}{Array.from({length:Math.max(0,5-(observation?.board.length??0))}).map((_,index)=><div className="card-slot" key={index}/>)}</div><div className="street-label">{observation?.street??'Loading'}</div><div className="seat hero-seat"><div className="hole-cards">{observation?.holeCards.map(card=><PlayingCard card={card} key={card}/>)??<><div className="card-slot"/><div className="card-slot"/></>}</div><div className="seat-meta"><span className="avatar hero-avatar">You</span><div><b>Your hand</b><small>{hero?chips(hero.stack):'—'}</small></div></div>{observation?.button===0&&<span className="dealer-chip hero-dealer">D</span>}</div>{busy&&<div className="table-loading"><LoaderCircle className="size-5 animate-spin"/>Thinking…</div>}</div></div>
      <div className="decision-dock"><div className="decision-copy"><span className="pulse-ring"/><div><strong>{mode==='review'?`Action ${reviewStep} of ${Math.max(0,(review?.events.length??1)-1)}`:terminal?`Result · ${observation?.result?.reason}`:'Your turn'}</strong><small>{mode==='review'?(reviewEvent?.action?`Player ${(reviewEvent.actorSeat??0)+1} · ${reviewEvent.action.type.replaceAll('-',' ')}`:'Ready to act'):terminal?`Final payouts: ${observation?.result?.payouts.map(chips).join(' / ')}`:`${observation?.legalActions.length??0} legal actions · Pot ${observation?chips(observation.pot):'—'}`}</small></div></div><div className="decision-actions">{mode==='review'?<><Button variant="outline" size="lg" disabled={reviewStep===0} onClick={()=>setReviewStep(value=>Math.max(0,value-1))}><ChevronLeft/>Previous</Button><Button size="lg" disabled={!review||reviewStep>=review.events.length-1} onClick={()=>setReviewStep(value=>Math.min((review?.events.length??1)-1,value+1))}>Next<ChevronRight/></Button></>:terminal?<Button size="lg" onClick={newHand}>Deal next hand</Button>:observation?.legalActions.filter(action=>action.type!=='raise-to').map(action=><Button key={action.type} variant={action.type==='fold'?'outline':action.type==='all-in'?'default':'secondary'} size="lg" disabled={busy} onClick={()=>void act(action)}>{actionLabel(action)}</Button>)}</div></div>
      {mode==='play'&&legalRaise&&<div className="raise-panel"><div className="raise-heading"><div><span className="eyebrow">Raise sizing</span><strong>{chips(clampedRaise)}</strong></div><Input aria-label="Raise-to amount in chips" type="number" min={legalRaise.minAmount??0} max={legalRaise.maxAmount??0} value={clampedRaise} onChange={event=>setRaiseAmount(Number(event.target.value))}/></div><Slider min={legalRaise.minAmount??0} max={legalRaise.maxAmount??0} step={Math.max(1,(observation?.bigBlind??100)/2)} value={[clampedRaise]} onValueChange={value=>setRaiseAmount(typeof value==='number'?value:value[0])}/><div className="raise-presets"><Button variant="outline" size="sm" onClick={()=>setRaiseAmount(potTarget(.5))}>½ pot</Button><Button variant="outline" size="sm" onClick={()=>setRaiseAmount(potTarget(.75))}>¾ pot</Button><Button variant="outline" size="sm" onClick={()=>setRaiseAmount(potTarget(1))}>Pot</Button><Button size="sm" disabled={busy} onClick={()=>void act(legalRaise,clampedRaise)}>Raise to {chips(clampedRaise)}</Button></div></div>}
    </div><aside className="coach-panel"><div className="coach-heading"><div><span className="eyebrow">Decision coach</span><h2>{activeStrategy?'Mixed strategy':mode==='review'?'Saved decision':'Think before revealing'}</h2></div><Sparkles className="size-5 text-[#d7a84c]"/></div>{activeStrategy?<div className="strategy-list">{activeStrategy.actions.map(item=><div className="strategy-item" key={`${item.abstractAction}-${item.legalAction?.type}`}><div><span>{item.abstractAction.replaceAll('-',' ')}</span><b>{Math.round(item.probability*100)}%</b></div><div className="strategy-track"><span style={{width:`${item.probability*100}%`}}/></div></div>)}<p className="strategy-meta">Experimental model · {activeStrategy.diagnostics.inferenceMs.toFixed(1)} ms</p>{activeStrategy.diagnostics.warnings.map(warning=><p className="model-warning" key={warning}>{warning}</p>)}</div>:<><div className="question-card"><BookOpen className="size-4"/><p>{mode==='review'?'Step through the hand to revisit each decision and the resulting table state.':'What does your range want to accomplish here—and which action keeps it hardest to exploit?'}</p></div><div className="metric-grid"><div><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div><span>Street</span><strong className="capitalize">{observation?.street??'—'}</strong></div></div><div className="range-block"><div className="range-row"><span>Recent action</span><b>{recentActions[0]?.type.replaceAll('-',' ')??'Blinds posted'}</b></div><div className="action-history">{recentActions.map((item,index)=><span key={`${item.seat}-${item.type}-${index}`}>P{item.seat+1} · {item.type.replaceAll('-',' ')} {item.amount?chips(item.amount):''}</span>)}</div></div></>}{mode==='play'&&!terminal&&<Button variant="outline" className="w-full" size="lg" onClick={revealStrategy} disabled={busy||!observation}><Sparkles/>{strategy?'Refresh strategy':'Reveal strategy'}</Button>}<p className="coach-note">Experimental advice is never used to grade you. The six-player checkpoint is shown only for comparison.</p></aside></section>
  </main>;
}
