'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, History, LoaderCircle, RotateCcw, Settings2, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';

const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:8000';
const SUITS:Record<string,string>={c:'♣',d:'♦',h:'♥',s:'♠'};
const MODEL_NAMES:Record<string,string>={'check-call-hu':'Check / call baseline','uniform-random-hu':'Uniform random baseline','fullhouse-deep-cfr-experimental-hu':'Fullhouse checkpoint'};
const HAND_RANKS=[['straight-flush','Straight flush'],['four-of-a-kind','Four of a kind'],['full-house','Full house'],['flush','Flush'],['straight','Straight'],['three-of-a-kind','Three of a kind'],['two-pair','Two pair'],['one-pair','One pair'],['high-card','High card']] as const;
type LegalAction={type:'fold'|'check'|'call'|'raise-to'|'all-in';amount:number|null;minAmount:number|null;maxAmount:number|null};
type Seat={seat:number;stack:number;streetCommitted:number;handCommitted:number;status:string};
type ActionRecord={street:string;seat:number;type:string;amount:number};
type Observation={seed:number;button:number;street:string;board:string[];pot:number;smallBlind:number;bigBlind:number;currentBet:number;amountToCall:number;toAct:number|null;heroSeat:number;holeCards:string[];bestFive:string[];bestFiveImportance:Record<string,number>;handCategory:string|null;seats:Seat[];actions:ActionRecord[];legalActions:LegalAction[];result:null|{reason:string;winners:number[];payouts:number[];revealedHoleCards?:string[][]}};
type HandPayload={sessionId:string;botProvider:string;observation:Observation};
type StrategyAction={abstractAction:string;probability:number;available?:boolean;legalAction:{type:string;amount:number|null}|null};
type Strategy={provider:{modelId:string};status:string;actions:StrategyAction[];modelActions?:StrategyAction[];diagnostics:{exactState:boolean;inferenceMs:number;warnings:string[];message:string|null}};
type Provider={id:string;version:string;experimental:boolean};
type HistoryItem={sessionId:string;seed:number;status:string;startedAt:string;result:null|{reason:string;winners:number[];payouts:number[]}};
type HistoryDetail=HistoryItem&{events:Array<{sequence:number;actorSeat:number|null;action:null|ActionRecord;observation:Observation;strategy:Strategy|null}>};

const chips=(value:number)=>`${(value/100).toFixed(value%100?1:0)} BB`;
const modelName=(id:string)=>MODEL_NAMES[id]??id;
function actionLabel(action:LegalAction){if(action.type==='call')return `Call ${chips(action.amount??0)}`;if(action.type==='all-in')return 'All-in';return action.type[0].toUpperCase()+action.type.slice(1);}
function strategyLabel(action:StrategyAction){if(action.legalAction?.type==='raise-to'&&action.legalAction.amount!==null)return `Raise to ${chips(action.legalAction.amount)}`;return action.abstractAction.replaceAll('-',' ');}
function raiseStops(minimum:number,maximum:number,bigBlind:number,targets:number[]){const values=new Set<number>([minimum,maximum,...targets]);for(const multiple of [2,2.5,3,4,5,7.5,10,15,20,30,50,75,100]){const value=Math.round(multiple*bigBlind);if(value>minimum&&value<maximum)values.add(value);}return [...values].sort((a,b)=>a-b);}
function PlayingCard({card,hidden=false,importance=0}:{card?:string;hidden?:boolean;importance?:number}){const value=card?`${card[0]}${SUITS[card[1]]??card[1]}`:'';const red=value.includes('♦')||value.includes('♥');return <div className={`playing-card ${hidden?'card-back':''} ${importance?`best-card best-card-${importance}`:''} ${red?'text-[#d9594c]':'text-[#15251f]'}`} aria-label={hidden?'Hidden card':value}>{hidden?<span className="card-back-mark">GT</span>:<span>{value}</span>}</div>;}

export default function GameClient(){
  const [hand,setHand]=useState<HandPayload|null>(null),[strategy,setStrategy]=useState<Strategy|null>(null),[providers,setProviders]=useState<Provider[]>([]);
  const [opponentProvider,setOpponentProvider]=useState('check-call-hu'),[trainerProvider,setTrainerProvider]=useState('fullhouse-deep-cfr-experimental-hu');
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[mode,setMode]=useState<'play'|'review'>('play');
  const [history,setHistory]=useState<HistoryItem[]>([]),[review,setReview]=useState<HistoryDetail|null>(null),[reviewStep,setReviewStep]=useState(0);
  const [raiseAmount,setRaiseAmount]=useState<number|null>(null),[showAllStrategy,setShowAllStrategy]=useState(false);
  const [highlightBestFive,setHighlightBestFive]=useState(true);
  const [autoStrategy,setAutoStrategy]=useState(true);
  const request=useCallback(async<T,>(path:string,options?:RequestInit):Promise<T>=>{const headers=new Headers(options?.headers);headers.set('Content-Type','application/json');const response=await fetch(`${API}${path}`,{...options,headers});const data:unknown=await response.json();if(!response.ok){const message=typeof data==='object'&&data!==null&&'error'in data?String(data.error):`Request failed (${response.status})`;throw new Error(message);}return data as T;},[]);
  const newHand=useCallback(async(provider=opponentProvider)=>{setBusy(true);setError(null);setStrategy(null);setShowAllStrategy(false);try{setHand(await request<HandPayload>('/v1/hands',{method:'POST',body:JSON.stringify({botProvider:provider})}));setRaiseAmount(null);}catch(reason){setError(reason instanceof Error?reason.message:'Could not start a hand');}finally{setBusy(false);}},[opponentProvider,request]);
  // oxlint-disable-next-line react/react-compiler, react-hooks/exhaustive-deps -- initial API synchronization
  useEffect(()=>{void Promise.all([newHand(),request<{providers:Provider[]}>('/v1/providers').then(result=>setProviders(result.providers))]);},[]);
  useEffect(()=>{if(!autoStrategy||mode!=='play'||!hand||hand.observation.street==='terminal'||hand.observation.toAct!==0)return;let cancelled=false;request<Strategy>(`/v1/hands/${hand.sessionId}/strategy`,{method:'POST',body:JSON.stringify({providerId:trainerProvider})}).then(result=>{if(!cancelled){setStrategy(result);setShowAllStrategy(false);}}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:'Strategy unavailable');});return()=>{cancelled=true;};},[autoStrategy,hand,mode,request,trainerProvider]);
  async function act(action:LegalAction,amount?:number){if(!hand)return;setBusy(true);setError(null);setStrategy(null);setShowAllStrategy(false);try{const body={type:action.type,...(action.type==='raise-to'?{amount:amount??action.minAmount}:{})};setHand(await request<HandPayload>(`/v1/hands/${hand.sessionId}/actions`,{method:'POST',body:JSON.stringify(body)}));setRaiseAmount(null);}catch(reason){setError(reason instanceof Error?reason.message:'Action failed');}finally{setBusy(false);}}
  async function revealStrategy(){if(!hand)return;setBusy(true);setError(null);try{setStrategy(await request<Strategy>(`/v1/hands/${hand.sessionId}/strategy`,{method:'POST',body:JSON.stringify({providerId:trainerProvider})}));setShowAllStrategy(false);}catch(reason){setError(reason instanceof Error?reason.message:'Strategy unavailable');}finally{setBusy(false);}}
  async function selectOpponent(provider:string){setOpponentProvider(provider);setMode('play');await newHand(provider);}
  async function openReview(){setMode('review');setBusy(true);setError(null);try{const result=await request<{hands:HistoryItem[]}>('/v1/history?limit=30');setHistory(result.hands);if(result.hands[0])await selectHistory(result.hands[0].sessionId);}catch(reason){setError(reason instanceof Error?reason.message:'History unavailable');}finally{setBusy(false);}}
  async function selectHistory(sessionId:string){const detail=await request<HistoryDetail>(`/v1/history/${sessionId}`);setReview(detail);setReviewStep(Math.max(0,detail.events.length-1));setStrategy(null);}
  const reviewEvent=review?.events[reviewStep],observation=mode==='review'?reviewEvent?.observation:hand?.observation;
  const hero=observation?.seats[0],opponent=observation?.seats[1],terminal=observation?.street==='terminal';
  const heroWon=terminal&&observation?.result?.winners.includes(0),opponentWon=terminal&&observation?.result?.winners.includes(1),tie=heroWon&&opponentWon;
  const opponentCards=terminal&&observation?.result?.reason==='showdown'?observation.result.revealedHoleCards?.[1]:undefined;
  const recentActions=useMemo(()=>observation?.actions.slice(-4).reverse()??[],[observation]);
  const activeStrategy=mode==='review'?reviewEvent?.strategy??null:strategy;
  const sortedStrategy=useMemo(()=>[...(activeStrategy?.modelActions??activeStrategy?.actions??[])].sort((a,b)=>b.probability-a.probability),[activeStrategy]);
  const visibleStrategy=showAllStrategy?sortedStrategy:sortedStrategy.slice(0,3);
  const legalRaise=mode==='play'?observation?.legalActions.find(item=>item.type==='raise-to'):undefined;
  const clampedRaise=legalRaise?Math.max(legalRaise.minAmount??0,Math.min(raiseAmount??legalRaise.minAmount??0,legalRaise.maxAmount??0)):0;
  const potTarget=(fraction:number)=>legalRaise?Math.max(legalRaise.minAmount??0,Math.min(Math.round((observation?.currentBet??0)+((observation?.pot??0)+(observation?.amountToCall??0))*fraction),legalRaise.maxAmount??0)):0;
  const sizingStops=legalRaise?raiseStops(legalRaise.minAmount??0,legalRaise.maxAmount??0,observation?.bigBlind??100,[potTarget(.5),potTarget(.75),potTarget(1)]):[];
  const activeStop=sizingStops.reduce((best,value,index)=>Math.abs(value-clampedRaise)<Math.abs(sizingStops[best]-clampedRaise)?index:best,0);
  const currentOpponentModel=hand?.botProvider??opponentProvider;
  const cardImportance=highlightBestFive?observation?.bestFiveImportance??{}:{};
  return <main className="app-shell">
    <header className="app-header"><div className="brand-lockup"><span className="brand-mark"><Activity className="size-4"/></span><div><p className="brand-name">Game Trainer</p><p className="brand-subtitle">Heads-up no-limit hold’em</p></div></div><nav className="mode-switch" aria-label="Application mode"><button className={`mode-pill ${mode==='play'?'mode-pill-active':''}`} onClick={()=>setMode('play')}>Play</button><button className="mode-pill" disabled>Train</button><button className={`mode-pill ${mode==='review'?'mode-pill-active':''}`} onClick={()=>void openReview()}>Review</button></nav><div className="header-actions"><span className="local-badge"><span className={`status-dot ${error?'status-error':''}`}/>{error?'Engine offline':'Local engine'}</span><Button variant="ghost" size="icon" aria-label="Settings" disabled><Settings2/></Button></div></header>
    {mode==='review'&&<section className="history-strip"><div><History className="size-4"/><strong>Saved hands</strong></div><div className="history-list">{history.map(item=><button key={item.sessionId} className={review?.sessionId===item.sessionId?'history-active':''} onClick={()=>void selectHistory(item.sessionId)}><b>Seed {item.seed}</b><span>{item.status==='terminal'?(item.result?.winners.includes(0)?'Won':'Complete'):'In progress'}</span></button>)}</div></section>}
    <section className="workspace"><aside className="hand-ranks"><div className="hand-ranks-heading"><div><span className="eyebrow">Poker hands</span><h2>Hand rankings</h2></div><Switch size="sm" aria-label="Highlight your best five cards" checked={highlightBestFive} onCheckedChange={setHighlightBestFive}/></div><p>Highlight best five</p><ol>{HAND_RANKS.map(([id,label],index)=><li key={id} className={highlightBestFive&&observation?.handCategory===id?'rank-active':''}><span>{index+1}</span><b>{label}</b></li>)}</ol>{observation?.handCategory?<div className="current-hand"><span>Your current hand</span><strong>{HAND_RANKS.find(([id])=>id===observation.handCategory)?.[1]}</strong></div>:<div className="current-hand current-hand-empty"><span>Your current hand</span><strong>Available on the flop</strong></div>}</aside><div className="table-column"><div className="session-bar"><div><span className="eyebrow">{mode==='review'?'Hand replay':'Practice hand'} · 100 BB {observation?`· Seed ${observation.seed}`:''}</span><h1>{mode==='review'?'Review the action line':tie?'Split pot':heroWon?'You win':opponentWon?'Opponent wins':'Choose your action'}</h1></div><Button variant="outline" size="sm" onClick={()=>{setMode('play');void newHand();}} disabled={busy}><RotateCcw/>{mode==='review'?'Back to play':'New hand'}</Button></div>
      {error&&<div className="error-banner"><TriangleAlert className="size-4"/><div><strong>Can’t reach the game engine</strong><span>{error}. Start the local API on port 8000, then try again.</span></div></div>}
      <div className="poker-table-wrap"><div className="poker-table"><div className="felt-grain"/><div className={`seat opponent-seat ${opponentWon?'winning-seat':''}`}><div className="seat-meta"><span className="avatar">B</span><div><b>{tie?'Split pot':opponentWon?'Winner':modelName(currentOpponentModel)}</b><small>{opponent?chips(opponent.stack):'—'}</small></div>{opponent?.streetCommitted?<span className="seat-bet">Bet {chips(opponent.streetCommitted)}</span>:null}</div><div className="hole-cards">{opponentCards?opponentCards.map(card=><PlayingCard card={card} key={card}/>):<><PlayingCard hidden/><PlayingCard hidden/></>}</div>{observation?.button===1&&<span className="dealer-chip">D</span>}</div><div className="pot-label"><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div className="board-cards">{observation?.board.map(card=><PlayingCard card={card} importance={cardImportance[card]??0} key={card}/>)}{Array.from({length:Math.max(0,5-(observation?.board.length??0))}).map((_,index)=><div className="card-slot" key={index}/>)}</div><div className="street-label">{observation?.street??'Loading'}</div><div className={`seat hero-seat ${heroWon?'winning-seat':''}`}><div className="hole-cards">{observation?.holeCards.map(card=><PlayingCard card={card} importance={cardImportance[card]??0} key={card}/>)??<><div className="card-slot"/><div className="card-slot"/></>}</div><div className="seat-meta"><span className="avatar hero-avatar">You</span><div><b>{tie?'Split pot':heroWon?'Winner':'Your hand'}</b><small>{hero?chips(hero.stack):'—'}</small></div>{hero?.streetCommitted?<span className="seat-bet">Bet {chips(hero.streetCommitted)}</span>:null}</div>{observation?.button===0&&<span className="dealer-chip hero-dealer">D</span>}</div>{terminal&&<div className={`result-banner ${heroWon?'result-win':''}`}><strong>{tie?'Pot split':heroWon?'You won the hand':'Opponent won the hand'}</strong><span>{observation?.result?.reason} · {observation?.result?.payouts.map(chips).join(' / ')}</span></div>}{busy&&<div className="table-loading"><LoaderCircle className="size-5 animate-spin"/>Thinking…</div>}</div></div>
      <div className="decision-dock"><div className="decision-copy"><span className="pulse-ring"/><div><strong>{mode==='review'?`Action ${reviewStep} of ${Math.max(0,(review?.events.length??1)-1)}`:terminal?`Hand complete · ${observation?.result?.reason}`:'Your turn'}</strong><small>{mode==='review'?(reviewEvent?.action?`Player ${(reviewEvent.actorSeat??0)+1} · ${reviewEvent.action.type.replaceAll('-',' ')}`:'Ready to act'):terminal?`Payouts ${observation?.result?.payouts.map(chips).join(' / ')}`:`To call ${chips(observation?.amountToCall??0)} · Pot ${chips(observation?.pot??0)}`}</small></div></div>{mode==='play'&&legalRaise&&<div className="raise-compact"><div className="raise-presets"><button onClick={()=>setRaiseAmount(potTarget(.5))}>½</button><button onClick={()=>setRaiseAmount(potTarget(.75))}>¾</button><button onClick={()=>setRaiseAmount(potTarget(1))}>Pot</button></div><div className="raise-slider"><Slider aria-label="Raise size" min={0} max={Math.max(0,sizingStops.length-1)} step={1} value={[activeStop]} onValueChange={value=>setRaiseAmount(sizingStops[typeof value==='number'?value:value[0]])}/><div className="raise-scale"><span>{chips(sizingStops[0]??0)}</span><span>{chips(sizingStops.at(-1)??0)}</span></div></div><Input aria-label="Raise-to amount in chips" type="number" min={legalRaise.minAmount??0} max={legalRaise.maxAmount??0} value={clampedRaise} onChange={event=>setRaiseAmount(Number(event.target.value))}/><Button size="sm" disabled={busy} onClick={()=>void act(legalRaise,clampedRaise)}>Raise {chips(clampedRaise)}</Button></div>}<div className="decision-actions">{mode==='review'?<><Button variant="outline" size="sm" disabled={reviewStep===0} onClick={()=>setReviewStep(value=>Math.max(0,value-1))}><ChevronLeft/>Previous</Button><Button size="sm" disabled={!review||reviewStep>=review.events.length-1} onClick={()=>setReviewStep(value=>Math.min((review?.events.length??1)-1,value+1))}>Next<ChevronRight/></Button></>:terminal?<Button size="sm" onClick={()=>void newHand()}>Deal next hand</Button>:observation?.legalActions.filter(action=>action.type!=='raise-to').map(action=><Button key={action.type} variant={action.type==='fold'?'outline':action.type==='all-in'?'default':'secondary'} size="sm" disabled={busy} onClick={()=>void act(action)}>{actionLabel(action)}</Button>)}</div></div>
    </div><aside className="coach-panel"><div className="model-control"><span>Opponent</span><Select value={opponentProvider} onValueChange={value=>void selectOpponent(value as string)}><SelectTrigger className="w-full"><SelectValue>{modelName(opponentProvider)}</SelectValue></SelectTrigger><SelectContent>{providers.map(provider=><SelectItem key={provider.id} value={provider.id}>{modelName(provider.id)}{provider.experimental?' · experimental':''}</SelectItem>)}</SelectContent></Select></div><div className="coach-heading"><div><span className="eyebrow">Strategy reference</span><h2>{activeStrategy?'Action mix':'Compare this decision'}</h2></div></div><div className="model-control"><span>Advice model</span><Select value={trainerProvider} onValueChange={value=>{setTrainerProvider(value as string);setStrategy(null);}}><SelectTrigger className="w-full"><SelectValue>{modelName(trainerProvider)}</SelectValue></SelectTrigger><SelectContent>{providers.map(provider=><SelectItem key={provider.id} value={provider.id}>{modelName(provider.id)}{provider.experimental?' · experimental':''}</SelectItem>)}</SelectContent></Select></div><div className="auto-strategy"><div><strong>Auto-show strategy</strong><span>Refresh at every decision</span></div><Switch aria-label="Automatically show strategy at every decision" checked={autoStrategy} onCheckedChange={setAutoStrategy}/></div>
      {activeStrategy?<div className="strategy-list">{visibleStrategy.map(item=><div className={`strategy-item ${item.available===false?'strategy-unavailable':''}`} key={`${item.abstractAction}-${item.legalAction?.type}-${item.legalAction?.amount}`}><div><span>{strategyLabel(item)}{item.available===false?' · unavailable':''}</span><b>{(item.probability*100).toFixed(item.probability<.01?1:0)}%</b></div><div className="strategy-track"><span style={{width:`${item.probability*100}%`}}/></div></div>)}{sortedStrategy.length>3&&<button className="strategy-expand" onClick={()=>setShowAllStrategy(value=>!value)}>{showAllStrategy?<><ChevronUp/>Show top 3</>:<><ChevronDown/>Show all {sortedStrategy.length} model actions</>}</button>}<p className="strategy-meta">Full model abstraction · {modelName(activeStrategy.provider.modelId)} · {activeStrategy.diagnostics.inferenceMs.toFixed(1)} ms</p>{activeStrategy.diagnostics.warnings.map(warning=><p className="model-warning" key={warning}>{warning}</p>)}</div>:<div className="coach-empty"><div className="metric-grid"><div><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div><span>Street</span><strong className="capitalize">{observation?.street??'—'}</strong></div></div><div className="range-block"><div className="range-row"><span>Last action</span><b>{recentActions[0]?.type.replaceAll('-',' ')??'Blinds posted'}</b></div><div className="action-history">{recentActions.map((item,index)=><span key={`${item.seat}-${item.type}-${index}`}>P{item.seat+1} · {item.type.replaceAll('-',' ')} {item.amount?chips(item.amount):''}</span>)}</div></div></div>}{mode==='play'&&!terminal&&!autoStrategy&&<Button variant="outline" className="w-full" size="sm" onClick={revealStrategy} disabled={busy||!observation}>Show strategy</Button>}<p className="coach-note">Baselines are not optimal play. The Fullhouse checkpoint is experimental and not validated for heads-up hold’em.</p>
    </aside></section>
  </main>;
}
