'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BookOpen, LoaderCircle, RotateCcw, Settings2, Sparkles, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';
const SUITS: Record<string, string> = { c: '♣', d: '♦', h: '♥', s: '♠' };
type LegalAction = { type: 'fold'|'check'|'call'|'raise-to'|'all-in'; amount:number|null; minAmount:number|null; maxAmount:number|null };
type Seat = { seat:number; stack:number; streetCommitted:number; handCommitted:number; status:string };
type Observation = { seed:number; button:number; street:string; board:string[]; pot:number; toAct:number|null; heroSeat:number; holeCards:string[]; seats:Seat[]; actions:Array<{street:string;seat:number;type:string;amount:number}>; legalActions:LegalAction[]; result:null|{reason:string;winners:number[];payouts:number[];revealedHoleCards?:string[][]} };
type HandPayload = { sessionId:string; observation:Observation };
type Strategy = { status:string; actions:Array<{abstractAction:string;probability:number;legalAction:{type:string;amount:number|null}|null}>; diagnostics:{exactState:boolean;inferenceMs:number;warnings:string[];message:string|null} };

const cardLabel = (card:string) => `${card[0]}${SUITS[card[1]] ?? card[1]}`;
const chips = (value:number) => `${(value/100).toFixed(value%100 ? 1 : 0)} BB`;
function actionLabel(action:LegalAction) { if(action.type==='raise-to') return `Raise · ${chips(action.minAmount ?? 0)}`; if(action.type==='call') return `Call · ${chips(action.amount ?? 0)}`; if(action.type==='all-in') return 'All-in'; return action.type[0].toUpperCase()+action.type.slice(1); }
function PlayingCard({card,hidden=false}:{card?:string;hidden?:boolean}) { const value=card?cardLabel(card):''; const red=value.includes('♦')||value.includes('♥'); return <div className={`playing-card ${hidden?'card-back':''} ${red?'text-[#d9594c]':'text-[#15251f]'}`} aria-label={hidden?'Hidden card':value}>{hidden?<span className="card-back-mark">GT</span>:<span>{value}</span>}</div>; }

export default function GameClient() {
  const [hand,setHand]=useState<HandPayload|null>(null); const [strategy,setStrategy]=useState<Strategy|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const request=useCallback(async<T,>(path:string,options?:RequestInit):Promise<T>=>{ const headers=new Headers(options?.headers); headers.set('Content-Type','application/json'); const response=await fetch(`${API}${path}`,{...options,headers}); const data:unknown=await response.json(); if(!response.ok){const message=typeof data==='object'&&data!==null&&'error' in data?String(data.error):`Request failed (${response.status})`;throw new Error(message);} return data as T; },[]);
  const newHand=useCallback(async()=>{ setBusy(true);setError(null);setStrategy(null);try{setHand(await request<HandPayload>('/v1/hands',{method:'POST',body:'{}'}));}catch(reason){setError(reason instanceof Error?reason.message:'Could not start a hand');}finally{setBusy(false);}},[request]);
  // oxlint-disable-next-line react/react-compiler -- initial network synchronization
  useEffect(()=>{void newHand();},[newHand]);
  async function act(action:LegalAction){if(!hand)return;setBusy(true);setError(null);setStrategy(null);try{const body={type:action.type,...(action.type==='raise-to'?{amount:action.minAmount}:{})};setHand(await request<HandPayload>(`/v1/hands/${hand.sessionId}/actions`,{method:'POST',body:JSON.stringify(body)}));}catch(reason){setError(reason instanceof Error?reason.message:'Action failed');}finally{setBusy(false);}}
  async function revealStrategy(){if(!hand)return;setBusy(true);setError(null);try{setStrategy(await request<Strategy>(`/v1/hands/${hand.sessionId}/strategy`,{method:'POST',body:'{}'}));}catch(reason){setError(reason instanceof Error?reason.message:'Strategy unavailable');}finally{setBusy(false);}}
  const observation=hand?.observation, hero=observation?.seats[0], opponent=observation?.seats[1], terminal=observation?.street==='terminal';
  const opponentCards=terminal&&observation?.result?.reason==='showdown'?observation.result.revealedHoleCards?.[1]:undefined;
  const recentActions=useMemo(()=>observation?.actions.slice(-5).reverse()??[],[observation]);
  return <main className="min-h-screen bg-background text-foreground">
    <header className="app-header"><div className="brand-lockup"><span className="brand-mark"><Activity className="size-4"/></span><div><p className="brand-name">Game Trainer</p><p className="brand-subtitle">Heads-up no-limit hold’em</p></div></div><nav className="mode-switch" aria-label="Application mode"><button className="mode-pill mode-pill-active">Play</button><button className="mode-pill" disabled>Train</button><button className="mode-pill" disabled>Review</button></nav><div className="header-actions"><span className="local-badge"><span className={`status-dot ${error?'status-error':''}`}/>{error?'Engine offline':'Local engine'}</span><Button variant="ghost" size="icon" aria-label="Settings" disabled><Settings2/></Button></div></header>
    <section className="workspace"><div className="table-column"><div className="session-bar"><div><span className="eyebrow">Practice hand · 100 BB {observation?`· Seed ${observation.seed}`:''}</span><h1>{terminal?(observation?.result?.winners.includes(0)?'Hand won':'Hand complete'):'Choose your action'}</h1></div><Button variant="outline" onClick={newHand} disabled={busy}><RotateCcw/>New hand</Button></div>
      {error&&<div className="error-banner"><TriangleAlert className="size-4"/><div><strong>Can’t reach the game engine</strong><span>{error}. Start the local API on port 8000, then try again.</span></div></div>}
      <div className="poker-table-wrap"><div className="poker-table"><div className="felt-grain"/><div className="seat opponent-seat"><div className="seat-meta"><span className="avatar">B</span><div><b>Trainer bot</b><small>{opponent?chips(opponent.stack):'—'}</small></div></div><div className="hole-cards">{opponentCards?opponentCards.map(card=><PlayingCard card={card} key={card}/>):<><PlayingCard hidden/><PlayingCard hidden/></>}</div>{observation?.button===1&&<span className="dealer-chip">D</span>}</div><div className="pot-label"><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div className="board-cards">{observation?.board.map(card=><PlayingCard card={card} key={card}/>)}{Array.from({length:Math.max(0,5-(observation?.board.length??0))}).map((_,index)=><div className="card-slot" key={index}/>)}</div><div className="street-label">{observation?.street??'Loading'}</div><div className="seat hero-seat"><div className="hole-cards">{observation?.holeCards.map(card=><PlayingCard card={card} key={card}/>)??<><div className="card-slot"/><div className="card-slot"/></>}</div><div className="seat-meta"><span className="avatar hero-avatar">You</span><div><b>Your hand</b><small>{hero?chips(hero.stack):'—'}</small></div></div>{observation?.button===0&&<span className="dealer-chip hero-dealer">D</span>}</div>{busy&&<div className="table-loading"><LoaderCircle className="size-5 animate-spin"/>Thinking…</div>}</div></div>
      <div className="decision-dock"><div className="decision-copy"><span className="pulse-ring"/><div><strong>{terminal?`Result · ${observation?.result?.reason}`:'Your turn'}</strong><small>{terminal?`Final payouts: ${observation?.result?.payouts.map(chips).join(' / ')}`:`${observation?.legalActions.length??0} legal actions · Pot ${observation?chips(observation.pot):'—'}`}</small></div></div><div className="decision-actions">{terminal?<Button size="lg" onClick={newHand}>Deal next hand</Button>:observation?.legalActions.map(action=><Button key={action.type} variant={action.type==='fold'?'outline':action.type==='raise-to'||action.type==='all-in'?'default':'secondary'} size="lg" disabled={busy} onClick={()=>void act(action)}>{actionLabel(action)}</Button>)}</div></div>
    </div><aside className="coach-panel"><div className="coach-heading"><div><span className="eyebrow">Decision coach</span><h2>{strategy?'Mixed strategy':'Think before revealing'}</h2></div><Sparkles className="size-5 text-[#d7a84c]"/></div>{strategy?<div className="strategy-list">{strategy.actions.map(item=><div className="strategy-item" key={`${item.abstractAction}-${item.legalAction?.type}`}><div><span>{item.abstractAction.replaceAll('-',' ')}</span><b>{Math.round(item.probability*100)}%</b></div><div className="strategy-track"><span style={{width:`${item.probability*100}%`}}/></div></div>)}<p className="strategy-meta">Experimental model · {strategy.diagnostics.inferenceMs.toFixed(1)} ms</p>{strategy.diagnostics.warnings.map(warning=><p className="model-warning" key={warning}>{warning}</p>)}</div>:<><div className="question-card"><BookOpen className="size-4"/><p>What does your range want to accomplish here—and which action keeps it hardest to exploit?</p></div><div className="metric-grid"><div><span>Pot</span><strong>{observation?chips(observation.pot):'—'}</strong></div><div><span>Street</span><strong className="capitalize">{observation?.street??'—'}</strong></div></div><div className="range-block"><div className="range-row"><span>Recent action</span><b>{recentActions[0]?.type.replaceAll('-',' ')??'Blinds posted'}</b></div><div className="action-history">{recentActions.map((item,index)=><span key={`${item.seat}-${item.type}-${index}`}>P{item.seat+1} · {item.type.replaceAll('-',' ')} {item.amount?chips(item.amount):''}</span>)}</div></div></>}{!terminal&&<Button variant="outline" className="w-full" size="lg" onClick={revealStrategy} disabled={busy||!observation}><Sparkles/>{strategy?'Refresh strategy':'Reveal strategy'}</Button>}<p className="coach-note">Experimental advice is never used to grade you. The six-player checkpoint is shown only for comparison.</p></aside></section>
  </main>;
}
